M48
; DRILL file KiCad 10.0.6 date 2026-09-25T08:16:39
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-25T08:16:39-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.794
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X20.287Y-22.389
X20.287Y-111.301
T2
X166.34Y-59.9
X166.34Y-111.9
M30
