#!/usr/bin/env python3
"""mkkio.py - os/kermit_io.asm -> os/kermit_io.c, /BIN/KERMIT's line I/O as a relocatable C byte array (2026-09-26).

  python3 mkkio.py              write os/kermit_io.c (os/Makefile runs it when the .asm changes)
  python3 mkkio.py --check      exit 1 if os/kermit_io.c is not what the .asm gives (tests/kermit/run.py)

y1cc has no inline assembly, and a Y1/OS program cannot know where the compiler puts an array, so the routines are
assembled twice with software/assembler/asm (ORG 0000H and ORG 1000H: the source's `ORG 0000H` line is rewritten)
and the two images compared: every byte that differs must be the high byte of a word that is 1000H larger in the
second image, i.e. an absolute address inside the code. The C file holds the ORG 0 bytes (kio[]), the offsets of
those words (kio_rel[], ending with 0: offset 0 is a BR opcode, never an address), and the offsets of the entries
and parameters as #defines (KIO_KRX, KIO_KBUF ..., from the assembler's cross-reference). kermit.c adds kio's
address to each listed word once, then calls kio + KIO_KRX with call()."""
import os, re, sys, shutil, subprocess, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "kermit_io.asm")
OUT = os.path.join(HERE, "kermit_io.c")
ASM = os.path.join(ROOT, "software/assembler/asm")
DEF = os.path.join(ROOT, "software/assembler/yacc1.def")
ENTRIES = ["KRX", "KTX", "KCRC", "KSUM", "KDEC", "KENC"]
PARAMS = ["KBUF", "KCNT", "KTIMO", "KTAB", "KOUT", "KROOM", "KC", "KTXT", "KRQ", "KEQ", "KCQ"]


def assemble(text, org, d):
    src = text.replace("        ORG 0000H", "        ORG %04XH" % org, 1)
    if src == text and org: sys.exit("mkkio: no `        ORG 0000H` line in %s" % SRC)
    open(os.path.join(d, "kio.asm"), "w").write(src)
    shutil.copy(DEF, d); open(os.path.join(d, "rcasm.rc"), "w").write("-h\n-x\n")
    lst = subprocess.run([ASM, "kio", "-d=yacc1"], cwd=d, capture_output=True, text=True).stdout
    if not re.search(r"^0 Errors", lst, re.M): sys.exit("mkkio: assembler errors:\n" + lst[-2000:])
    mem = {}
    for line in open(os.path.join(d, "kio.img")):
        if not line.startswith(":") or line[7:9] != "00": continue
        n, a = int(line[1:3], 16), int(line[3:7], 16)
        for i in range(n): mem[a + i] = int(line[9 + 2 * i:11 + 2 * i], 16)
    image = bytes(mem.get(org + i, 0) for i in range(max(mem) - org + 1))
    labels = {m.group(2): int(m.group(1), 16) - org for m in re.finditer(r"^([0-9a-f]{4})h: (\w+)", lst, re.M)}
    return image, labels


def build():
    """-> (the ORG 0 image, the ORG 1000H image, the labels' offsets)"""
    text = open(SRC).read()
    d = tempfile.mkdtemp()
    try:
        a, la = assemble(text, 0, d)
        b, _ = assemble(text, 0x1000, d)
    finally:
        shutil.rmtree(d)
    return a, b, la


def generate():
    a, b, la = build()
    if len(a) != len(b): sys.exit("mkkio: the two images differ in length")
    rel, i = [], 0
    while i < len(a):
        if a[i] != b[i]:
            if i + 1 >= len(a) or b[i] != (a[i] + 0x10) & 255 or a[i + 1] != b[i + 1]:
                sys.exit("mkkio: byte %d differs in a way that is not an address" % i)
            rel.append(i); i += 2
        else: i += 1
    for k in ENTRIES + PARAMS:
        if k not in la: sys.exit("mkkio: label %s missing" % k)
    out = ["/* kermit_io.c - GENERATED by os/mkkio.py from os/kermit_io.asm: do not edit (see those two for what it is).",
           "   /BIN/KERMIT's line I/O, %d bytes assembled at 0000H; kio_rel[] lists the offsets of its absolute" % len(a),
           "   address words (0 ends it), which kermit.c relocates to where kio[] is before the first call. The",
           "   entries (call(kio + KIO_KRX) ...) and the parameters (pokew(kio + KIO_KBUF, ...)) are offsets in kio[]. */"]
    out += ["#define KIO_%-6s %d" % (k, la[k]) for k in ENTRIES + PARAMS]
    out.append("char kio[] = {")
    for j in range(0, len(a), 16):
        out.append("    " + ", ".join(str(x) for x in a[j:j + 16]) + ("," if j + 16 < len(a) else ""))
    out.append("};")
    out.append("int kio_rel[] = {" + ", ".join(str(x) for x in rel + [0]) + "};")
    return "\n".join(out) + "\n"


def main():
    s = generate()
    if "--check" in sys.argv[1:]:
        if not os.path.exists(OUT) or open(OUT).read() != s: sys.exit("mkkio: os/kermit_io.c is stale: run make -C os")
        print("mkkio: os/kermit_io.c matches os/kermit_io.asm"); return
    open(OUT, "w").write(s)
    print("mkkio: os/kermit_io.c, %d bytes" % s.count(","))


if __name__ == "__main__":
    main()
