#!/usr/bin/env python3
"""mkstrings.py - os/strings.txt -> an assembler include of NUL-terminated byte strings (2026-09-23).

  python3 mkstrings.py strings.txt > build/asm/y1os_str.inc

Each line `LABEL "text"` becomes `LABEL:` and `DB` lines of up to 16 numeric bytes ending with a 0. The RC/asm
assembler upper-cases every source line before it matches it, so `DB "text"` would print TEXT; numbers keep the case
(docs/programming/ASSEMBLER.md, quirk 1). The text runs from the first to the last double quote on the line (so it
may itself hold quotes); blank lines and lines starting with # are skipped. Labels: letters, digits, _; at most 29
characters (a 30-character label crashes the assembler)."""
import re, sys


def main():
    if len(sys.argv) != 2: sys.exit(__doc__)
    out, seen = ["; generated by os/mkstrings.py from %s - do not edit" % sys.argv[1]], set()
    for n, line in enumerate(open(sys.argv[1], encoding="latin1"), 1):
        s = line.rstrip("\n")
        if not s.strip() or s.lstrip().startswith("#"): continue
        m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s+"(.*)"\s*$', s)
        if not m: sys.exit("mkstrings: %s:%d: expected LABEL \"text\"" % (sys.argv[1], n))
        lab, text = m.group(1), m.group(2)
        if len(lab) > 29: sys.exit("mkstrings: %s:%d: label %s is over 29 characters" % (sys.argv[1], n, lab))
        if lab.upper() in seen: sys.exit("mkstrings: %s:%d: label %s twice" % (sys.argv[1], n, lab))
        seen.add(lab.upper())
        bs = [ord(c) for c in text] + [0]
        if any(b > 255 for b in bs): sys.exit("mkstrings: %s:%d: not a byte string" % (sys.argv[1], n))
        out.append("%s:                               ; %s" % (lab, text.replace(";", ",")))
        out += ["        DB " + ",".join(str(b) for b in bs[i:i + 16]) for i in range(0, len(bs), 16)]
    print("\n".join(out))


if __name__ == "__main__":
    main()
