; Author: Claude (Anthropic) for Ken Rother's YACC1 project, 2026
;
; pushr.asm - bench diagnostic (2026-10-10): the bench's isa test popped $99B3 (and once $AB99) for a pushed $ABCD on
; the machine, and every compiled program printed wrong decimal numbers (rt_divmod pushes and pops words); both
; emulators are right. First run on the machine: PUSHR/POPR words came back wrong (mostly the high byte, data
; dependent: $5AA5 always right), single-byte PUSH/POP always right. This version separates the steps, two passes each:
;   E  MVIW R7,w then showr7 (no stack, no move): the print path itself
;   F  MVIW R3,w / MOVRR R3,R7 (card 0 -> card 1) / showr7: the register move used to print
;   W  MVIW R3,w / PUSHR R3, then the two pushed bytes read with LDAVR through a copy of SP (R5) at SP+1 and SP+2
;      and printed (hi lo), then POPR R3 to drop them: what PUSHR wrote
;   R  the word built in memory below SP by single-byte PUSHes (lo then hi, as PUSHR leaves it), then POPR R3,
;      MOVRR R3,R7, showr7: what POPR reads from a correct stack
;   A  PUSHR R3 / MVIW R3,0 / POPR R3 / MOVRR R3,R7 / showr7, as before
; Expected: every line the eight words $ABCD $1234 $0000 $FFFF $5AA5 $00FF $FF00 $8001.
; Load with tools/monload.py --go 3000. Hex written as numbers: the assembler upper-cases every source line.
;
stringout:  EQU 0ffc0h
charout:    EQU 0ffc4h
showr7:     EQU 0ffd4h
showbytea:  EQU 0ffe0h

        ORG 3000h
start:
        MVIW R7,s_e
        JSR stringout
        MVIW R7,0ABCDh
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,01234h
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,00000h
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,0FFFFh
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,05AA5h
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,000FFh
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,0FF00h
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,08001h
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 13
        JSR charout
        LDAI 10
        JSR charout
        MVIW R7,0ABCDh
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,01234h
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,00000h
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,0FFFFh
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,05AA5h
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,000FFh
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,0FF00h
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R7,08001h
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 13
        JSR charout
        LDAI 10
        JSR charout
        MVIW R7,s_f
        JSR stringout
        MVIW R3,0ABCDh
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,01234h
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,00000h
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,0FFFFh
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,05AA5h
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,000FFh
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,0FF00h
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,08001h
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 13
        JSR charout
        LDAI 10
        JSR charout
        MVIW R3,0ABCDh
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,01234h
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,00000h
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,0FFFFh
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,05AA5h
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,000FFh
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,0FF00h
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,08001h
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 13
        JSR charout
        LDAI 10
        JSR charout
        MVIW R7,s_w
        JSR stringout
        MVIW R3,0ABCDh
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,01234h
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,00000h
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,0FFFFh
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,05AA5h
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,000FFh
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,0FF00h
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,08001h
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        LDAI 13
        JSR charout
        LDAI 10
        JSR charout
        MVIW R3,0ABCDh
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,01234h
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,00000h
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,0FFFFh
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,05AA5h
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,000FFh
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,0FF00h
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        MVIW R3,08001h
        PUSHR R3
        MOVRR R1,R5
        INCR R5
        LDAVR R5
        STA c2
        INCR R5
        LDAVR R5
        STA c1
        POPR R3
        LDA c1
        JSR showbytea
        LDA c2
        JSR showbytea
        LDAI 32
        JSR charout
        LDAI 13
        JSR charout
        LDAI 10
        JSR charout
        MVIW R7,s_r
        JSR stringout
        LDAI 0ABh
        PUSH
        LDAI 0CDh
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 012h
        PUSH
        LDAI 034h
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 000h
        PUSH
        LDAI 000h
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 0FFh
        PUSH
        LDAI 0FFh
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 05Ah
        PUSH
        LDAI 0A5h
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 000h
        PUSH
        LDAI 0FFh
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 0FFh
        PUSH
        LDAI 000h
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 080h
        PUSH
        LDAI 001h
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 13
        JSR charout
        LDAI 10
        JSR charout
        LDAI 0ABh
        PUSH
        LDAI 0CDh
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 012h
        PUSH
        LDAI 034h
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 000h
        PUSH
        LDAI 000h
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 0FFh
        PUSH
        LDAI 0FFh
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 05Ah
        PUSH
        LDAI 0A5h
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 000h
        PUSH
        LDAI 0FFh
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 0FFh
        PUSH
        LDAI 000h
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 080h
        PUSH
        LDAI 001h
        PUSH
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 13
        JSR charout
        LDAI 10
        JSR charout
        MVIW R7,s_a
        JSR stringout
        MVIW R3,0ABCDh
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,01234h
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,00000h
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,0FFFFh
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,05AA5h
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,000FFh
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,0FF00h
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,08001h
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 13
        JSR charout
        LDAI 10
        JSR charout
        MVIW R3,0ABCDh
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,01234h
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,00000h
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,0FFFFh
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,05AA5h
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,000FFh
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,0FF00h
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        MVIW R3,08001h
        PUSHR R3
        MVIW R3,0
        POPR R3
        MOVRR R3,R7
        JSR showr7
        LDAI 32
        JSR charout
        LDAI 13
        JSR charout
        LDAI 10
        JSR charout
        RET
c1:     DB 0
c2:     DB 0
s_e:    DB 13,10,"E MVIW R7 + SHOWR7:",13,10,0
s_f:    DB 13,10,"F MOVRR R3,R7:",13,10,0
s_w:    DB 13,10,"W BYTES PUSHR WROTE (HI LO):",13,10,0
s_r:    DB 13,10,"R POPR OF BYTES PUSHED ONE AT A TIME:",13,10,0
s_a:    DB 13,10,"A PUSHR/POPR R3:",13,10,0
