#!/bin/sh
# build.sh - build and verify the YACC1 memory card v2.0 (v1.3 + the CF section) and its placement options (2026-09-24).
#
#   hardware/cards/memory/kicad/v2.0/build.sh                 schematic + every option in placements.py
#   OPTIONS="a c" hardware/cards/memory/kicad/v2.0/build.sh   only those options
#
# 1 gen_mem_v2.py sch: schematic (v1.3 sheets 1-6 + sheet 7 CF) + project + libraries
# 2 ERC (must equal v1.3's list + the one designed-in SRST single-pin label; the six bus labels that became global
#   lose their v1.3 "isolated label" warnings)
# 3 per option: board from v1.3 + the fabricated positions of IC26-IC29/RN5/RN6 + the option's moves + CF placement;
#   trim the v1.3 copper the moves broke (DRC-driven); refill the GND/VCC planes; placement check (no new body
#   overlaps, pads clear of the edge, the fabricated IC15 spot free, no tall part in the TAODAN keep-low zone); DRC
#   with schematic parity; review images: <option>-render-top.png (3D, adapter zones shown on silk) and
#   <option>-placement.png (2D: copper, silk, adapter zones, ratsnest from DRC's unconnected items)
# 4 netlist proof: v2.0 schematic = v1.3 schematic + CF section, and every board = the schematic (check_netlist.py)
# 5 schematic PDF, BOM
# The CF section is NOT routed (placement review first). Exit status non-zero if a gate fails.
HERE=$(cd "$(dirname "$0")" && pwd)
PYK=/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/3.9/bin/python3
CLI=/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli
INK=/Applications/Inkscape.app/Contents/MacOS/inkscape
P=memory-v2.0
R="$HERE/reports"
OPTIONS=${OPTIONS:-"a b c"}
export PYTHONDONTWRITEBYTECODE=1
q() { grep -vE 'Debug|assert|wxApp|traits|Fontconfig|memory leak|^$'; }
fail=0
mkdir -p "$R"
cd "$HERE" || exit 1
TMP=$(mktemp -d /tmp/memory-v2-build.XXXXXX)
trap 'rm -rf "$TMP"' EXIT
# v1.3 is read from a scratch copy, so no KiCad run can leave a file in ../v1.3 (it is regenerated by its own tool)
cp -R ../v1.3 "$TMP/v13"
OLD="$TMP/v13/memory-v1.3"

echo "== 1  schematic (gen_mem_v2.py sch) =="
"$PYK" gen_mem_v2.py sch 2>&1 | q || exit 1
"$CLI" sch export netlist --format kicadsexpr -o "$R/$P.net" "$P.kicad_sch" >/dev/null 2>&1
"$CLI" sch export netlist --format kicadsexpr -o "$TMP/v1.3.net" "$OLD.kicad_sch" >/dev/null 2>&1

echo "== 2  ERC =="
"$CLI" sch erc --severity-all -o "$R/$P-erc.rpt" "$P.kicad_sch" >/dev/null 2>&1
"$CLI" sch erc --severity-all --format json -o "$R/$P-erc.json" "$P.kicad_sch" >/dev/null 2>&1
"$CLI" sch erc --severity-all --format json -o "$TMP/v1.3-erc.json" "$OLD.kicad_sch" >/dev/null 2>&1
python3 - "$R/$P-erc.json" "$TMP/v1.3-erc.json" <<'EOF' | tee "$R/erc-summary.txt" || fail=1
import json, sys, collections
def load(p):
    c = collections.Counter()
    for s in json.load(open(p))["sheets"]:
        for v in s["violations"]:
            c[(v["severity"], v["type"], tuple(i["description"] for i in v["items"]))] += 1
    return c
v2, v1 = load(sys.argv[1]), load(sys.argv[2])
new, gone = v2 - v1, v1 - v2
by = lambda c: dict(collections.Counter((k[0], k[1]) for k in c.elements()))
print("  ERC v2.0: %d violations %s" % (sum(v2.values()), by(v2)))
print("  ERC v1.3: %d violations (the Eagle-conversion residue, ../v1.3/README.md)" % sum(v1.values()))
print("  new on v2.0: %s" % ([(k[1], k[2]) for k in new] or "none"))
print("  gone on v2.0: %s" % ([(k[1], k[2]) for k in gone] or "none"))
unexpected = [k for k in new if not (k[1] == "isolated_pin_label" and k[2] == ("Label 'SRST'",))]
GLOBAL = {"Label '%s'" % n for n in ["IO-ADDR0", "IO-ADDR1", "IO-ADDR2", "IO-ADDR3", "-IO-RD", "-IO-WR"]}
odd_gone = [k for k in gone if not (k[1] == "isolated_pin_label" and len(k[2]) == 1 and k[2][0] in GLOBAL)]
print("  unexplained: %d new, %d gone -> %s" % (len(unexpected), len(odd_gone),
                                                 "PASS" if not unexpected and not odd_gone else "FAIL"))
sys.exit(0 if not unexpected and not odd_gone else 1)
EOF

"$CLI" pcb drc --schematic-parity --severity-all --format json -o "$TMP/v1.3-drc.json" "$OLD.kicad_pcb" >/dev/null 2>&1

echo "== 3   reference board: v1.3 + the fabricated positions of IC26-IC29 / RN5 / RN6, no CF section =="
# the converted v1.3 board keeps those six parts outside the outline; on the board they land on stale v1.3 copper
# (the tree's Eagle board is an earlier save than the fabricated card). What that costs is not the CF section's doing,
# so the options are measured against this board.
"$PYK" gen_mem_v2.py board base "$R/$P.net" "$TMP/base.kicad_pcb" 2>&1 | q | sed 's/^/  /'
"$PYK" gen_mem_v2.py trim "$TMP/base.kicad_pcb" "$OLD.kicad_pcb" 2>&1 | q | sed 's/^/  /'
"$PYK" gen_mem_v2.py refill "$TMP/base.kicad_pcb" 2>&1 | q
rm -rf "$TMP/p"; mkdir "$TMP/p"
cp -R "$HERE"/*.kicad_sch "$HERE/$P.kicad_pro" "$HERE"/*-lib-table "$HERE"/memory-v1.3-eagle.* "$TMP/p/"
cp "$TMP/base.kicad_pcb" "$TMP/p/$P.kicad_pcb"
"$CLI" pcb drc --severity-all --format json -o "$TMP/base-drc.json" "$TMP/p/$P.kicad_pcb" >/dev/null 2>&1
python3 - "$TMP/base-drc.json" "$TMP/base.kicad_pcb" <<'EOF' | tee "$R/base-summary.txt" | sed 's/^/  /'
import json, sys, re
d = json.load(open(sys.argv[1]))
tot = sum(((u["items"][0]["pos"]["x"] - u["items"][1]["pos"]["x"]) ** 2 +
           (u["items"][0]["pos"]["y"] - u["items"][1]["pos"]["y"]) ** 2) ** 0.5
          for u in d.get("unconnected_items", []) if len(u["items"]) == 2)
kept = len(re.findall(r"^\t\((segment|via|arc)\b", open(sys.argv[2]).read(), re.M))
print("reference: %d unrouted v1.3 connections (%.0f mm of airwire); v1.3 copper items kept %d of 1048"
      % (len(d.get("unconnected_items", [])), tot, kept))
EOF
boards=""
for o in $OPTIONS; do
  B="$P-option-$o.kicad_pcb"
  echo "== 3$o  option $o =="
  "$PYK" gen_mem_v2.py board "$o" "$R/$P.net" 2>&1 | q || { fail=1; continue; }
  "$PYK" gen_mem_v2.py trim "$B" "$OLD.kicad_pcb" 2>&1 | q | sed 's/^/  /'
  "$PYK" gen_mem_v2.py refill "$B" 2>&1 | q
  "$PYK" gen_mem_v2.py check "$B" "$o" 2>&1 | q | tee "$R/option-$o-placement-check.txt" | sed 's/^/  /'
  grep -q ": OK" "$R/option-$o-placement-check.txt" || fail=1
  cp "$HERE/$P.kicad_pro" "$HERE/$P-option-$o.kicad_pro"
  # DRC with schematic parity: the board needs the schematic beside it under the same name
  rm -rf "$TMP/p"; mkdir "$TMP/p"
  cp -R "$HERE"/*.kicad_sch "$HERE/$P.kicad_pro" "$HERE"/*-lib-table "$HERE"/memory-v1.3-eagle.* "$TMP/p/"
  cp "$B" "$TMP/p/$P.kicad_pcb"
  "$CLI" pcb drc --schematic-parity --severity-all --format json -o "$R/option-$o-drc.json" "$TMP/p/$P.kicad_pcb" >/dev/null 2>&1
  python3 - "$R/option-$o-drc.json" "$TMP/v1.3-drc.json" "$B" "$TMP/base-drc.json" "$TMP/base.kicad_pcb" <<'EOF' | tee "$R/option-$o-drc-summary.txt" | sed 's/^/  /' || fail=1
import json, sys, collections, re
d, b, ref = json.load(open(sys.argv[1])), json.load(open(sys.argv[2])), json.load(open(sys.argv[4]))
c = collections.Counter(v["type"] for v in d["violations"])
cb = collections.Counter(v["type"] for v in b["violations"])
COSMETIC = {"silk_overlap", "silk_edge_clearance", "silk_over_copper", "text_height", "text_thickness",
            "lib_footprint_mismatch", "lib_footprint_issues"}
copper = {t: n for t, n in c.items() if t not in COSMETIC and n > cb.get(t, 0)}
# parity: v1.3's own (run beside its converted schematic) has the Eagle board values / fields; anything beyond is new
bpar = {(x["type"], x["description"]) for x in b.get("schematic_parity", []) if x["type"] != "net_conflict"}
newpar = [x["description"] for x in d.get("schematic_parity", []) if (x["type"], x["description"]) not in bpar]
print("     schematic parity: %d items (v1.3: %d); new: %s" % (len(d.get("schematic_parity", [])),
                                                             len(b.get("schematic_parity", [])), newpar or "none"))
kept = len(re.findall(r"^\t\((segment|via|arc)\b", open(sys.argv[3]).read(), re.M))
print("DRC: %s" % dict(sorted(c.items())))
print("     v1.3 had %s" % dict(sorted(cb.items())))
# ratsnest: all of it, and the part that touches a CF part (the CF section is not routed)
CF = r"\b(IC3[0-4]|J2|J3|JP2|RN9|R1[0-4]|LED1|C2[5-9]|C30)\b"
def rats(dd):
    n = cf = 0; tot = tcf = 0.0
    for u in dd.get("unconnected_items", []):
        its = u["items"]
        if len(its) != 2:
            continue
        L = ((its[0]["pos"]["x"] - its[1]["pos"]["x"]) ** 2 + (its[0]["pos"]["y"] - its[1]["pos"]["y"]) ** 2) ** 0.5
        n += 1; tot += L
        if any(re.search(r" of " + CF, i["description"]) for i in its):
            cf += 1; tcf += L
    return n, tot, cf, tcf
n, tot, cf, tcf = rats(d)
nr, totr, _, _ = rats(ref)
kref = len(re.findall(r"^\t\((segment|via|arc)\b", open(sys.argv[5]).read(), re.M))
print("     ratsnest %d airwires (%.0f mm): %d touch a CF part (%.0f mm); the other %d (%.0f mm) join v1.3 pads only "
      "(reference board: %d, %.0f mm; fewer here because the ratsnest of a shared net now also runs via CF pads)"
      % (n, tot, cf, tcf, n - cf, tot - tcf, nr, totr))
print("     v1.3 copper items (tracks + vias) kept %d of 1048 (reference board %d -> %d more removed by this option)"
      % (kept, kref, kref - kept))
print("     non-cosmetic violations beyond v1.3's: %s -> %s" % (copper or "none", "PASS" if not copper and not newpar else "FAIL"))
sys.exit(0 if not copper and not newpar else 1)
EOF
  # review images
  "$PYK" gen_mem_v2.py review "$B" "$TMP/r.kicad_pcb" render 2>&1 | q
  "$CLI" pcb render --side top --width 2000 --height 1400 -o "$HERE/$P-option-$o-render-top.png" "$TMP/r.kicad_pcb" >/dev/null 2>&1 \
    && echo "  render -> $P-option-$o-render-top.png"
  "$PYK" gen_mem_v2.py review "$B" "$TMP/p2.kicad_pcb" plot 2>&1 | q | sed 's/^/  /'
  "$CLI" pcb export svg --mode-single --page-size-mode 2 --exclude-drawing-sheet \
    -l Edge.Cuts,F.Cu,B.Cu,F.Silkscreen,User.Drawings,User.Comments,User.Eco1 -o "$TMP/p2.svg" "$TMP/p2.kicad_pcb" >/dev/null 2>&1
  "$INK" "$TMP/p2.svg" --export-type=png --export-width=2400 --export-background=white \
    --export-filename="$HERE/$P-option-$o-placement.png" >/dev/null 2>&1 && echo "  plot   -> $P-option-$o-placement.png"
  boards="$boards $B"
done

echo "== 4  netlist proof =="
python3 check_netlist.py "$R/$P.net" "$TMP/v1.3.net" "$OLD.kicad_pcb" $boards | tee "$R/netlist-proof.txt" | sed 's/^/  /'
grep -q "^RESULT: MATCH" "$R/netlist-proof.txt" || fail=1

echo "== 5  schematic PDF, BOM =="
"$CLI" sch export pdf -o "$HERE/$P-schematic.pdf" "$P.kicad_sch" >/dev/null 2>&1 && echo "  schematic PDF -> $P-schematic.pdf"
"$CLI" sch export bom --fields 'Reference,Value,Footprint,${QUANTITY}' --labels 'Refs,Value,Footprint,Qty' \
  --group-by 'Value,Footprint' --sort-field 'Reference' -o "$HERE/$P-bom.csv" "$P.kicad_sch" >/dev/null 2>&1 \
  && echo "  BOM -> $P-bom.csv ($(($(wc -l < "$HERE/$P-bom.csv") - 1)) lines)"
rm -f "$HERE"/*.kicad_prl "$HERE/fp-info-cache"

[ $fail -eq 0 ] && echo "== BUILD PASS ==" || echo "== BUILD FAIL (see above) =="
exit $fail
