#!/usr/bin/env python3
"""gen_relayout.py - the RE-LAYOUT boards of the YACC1 memory card v2.0 (2026-09-24): the whole card placed again from
scratch with the CF section designed in, and a trial autoroute of each placement option.

Ken's decision (2026-09-24): keep the circuit (the v2.0 netlist exactly: the built card v1.3 incl. IC15 + the CF
section), discard the built card's placement and copper. Kept from the built card: the board outline, the bus connector
X1 (position, orientation, its mounting holes; the card plugs into the same backplane), the 4-layer stack-up with the
solid In1 GND and In2 VCC planes (their outlines too). Signals on F.Cu and B.Cu only; every IC power pin reaches its
plane through its own through-hole pad (thermal relief); no power track is routed.

Run with KiCad's bundled Python (pcbnew); build.sh does, in this order per option:

  gen_relayout.py board <opt> <schematic .net>      -> options-top-edge-J2/memory-v2.0-relayout-<opt>.kicad_pcb (+ .kicad_pro,
                                                       .kicad_dru; the top-edge record since the standoff decision)
        the built board with every track and via removed; every pad on its v2.0 schematic net (as gen_mem_v2.py board);
        the CF footprints added; EVERY part except X1 placed from relayout_placements.py; the built card's silkscreen
        labels moved with their parts (U$1 block labels, JP1 labels), title V2.0, "CF: P8/P9" beside J2, LED/jumper
        labels; the TAODAN adapter strip + keep-low zone on User.Drawings; the planes' thermal reliefs; design rules
        (RULES below) in the project and in the .kicad_dru. C20-C23 (removed from the circuit on 2026-09-24, after
        these boards were made) stay on them as the built board has them: the option boards are the pre-removal review
        record (check_netlist.py --records, build.sh parity_new ... record)
  gen_relayout.py refill <pcb>                      -> the planes refilled (every new pad on GND/VCC gets its relief)
  gen_relayout.py check <pcb> <opt>                 -> placement check (overlaps, edge, keep-low zone, X1 = built)
  gen_relayout.py review <pcb> <out> render|plot    -> review copies (gen_mem_v2.py review_copy)
  gen_relayout.py dsn <pcb> <dsn>                   -> Specctra DSN of a TWO-signal-layer copy (the planes carry
                                                       GND/VCC: their net class Power is not routed, -inc Power)
  gen_relayout.py ses <pcb> <ses> <out>             -> the trial-routed board (Freerouting's copper on the 4-layer board)
  gen_relayout.py stats <pcb> <drc.json> [<opt>]    -> the trial-route numbers (unrouted, vias, length, DRC copper)
"""
import os, sys, re, json, math, subprocess, collections

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_mem_v2 as GM                                     # noqa: E402  (the v2.0 schematic's board helpers)
import mem_v2_netlist as NL                                 # noqa: E402
import relayout_placements as RP                            # noqa: E402
gen_cf = GM.gen_cf

PROJ = GM.PROJ
CLI = GM.CLI
G = 2.54

# the re-layout design rules (Ken 2026-09-24: wider than the built card's 6 mil tracks / 5 mil clearance)
RULES = dict(track=0.25, clearance=0.2, via=0.8, via_drill=0.4, edge=0.5, hole_to_hole=0.5, hole_clearance=0.25,
             annular=0.2, plane_clearance=0.3, thermal_gap=0.4, thermal_spoke=0.5)
DRU = """(version 1)
# generated by gen_relayout.py: the memory card v2.0 RE-LAYOUT rules (2026-09-24). The project's net classes say the same:
#   Default = every signal net: track 0.25 mm (10 mil), clearance 0.2 mm, via 0.8 / 0.4 mm
#   Power   = GND, VCC: NOT routed as tracks - every power pin is a through-hole pad on the In1 GND / In2 VCC plane
# Planes: 0.3 mm clearance (antipads), thermal reliefs 0.4 mm gap / 0.5 mm spokes. Copper to board edge 0.5 mm.
(rule "signal tracks 0.25 mm"
\t(constraint track_width (min 0.25mm) (opt 0.25mm))
\t(condition "A.Type == 'track'"))
(rule "clearance 0.2 mm"
\t(constraint clearance (min 0.2mm)))
(rule "vias 0.8 / 0.4 mm"
\t(constraint via_diameter (min 0.8mm))
\t(constraint hole_size (min 0.4mm))
\t(condition "A.Type == 'via'"))
(rule "plane antipads 0.3 mm"
\t(constraint clearance (min 0.3mm))
\t(condition "A.Type == 'zone' && (A.Layer == 'In1.Cu' || A.Layer == 'In2.Cu')"))
"""


# the top-edge options and the board made from option B (the record since the standoff decision, Ken 2026-09-24)
TOPEDGE = os.path.join(HERE, "options-top-edge-J2")


def fname(opt, kind="kicad_pcb"):
    return os.path.join(TOPEDGE, "%s-relayout-%s.%s" % (PROJ, opt, kind))


def write_project(opt, name=None):
    """the re-layout rules into <name or memory-v2.0-relayout-<opt>>.kicad_pro / .kicad_dru, on the base of the v2.0
    project gen_mem_v2.py sch wrote (the built card's project, whose top-level sheet list is not this project's)"""
    pro = json.load(open(os.path.join(HERE, PROJ + ".kicad_pro")))
    out = os.path.join(HERE, name) if name else fname(opt, "kicad_pro")[:-len(".kicad_pro")]
    pro["meta"]["filename"] = os.path.basename(out) + ".kicad_pro"
    if os.path.basename(out) != PROJ:
        pro.get("schematic", {})["top_level_sheets"] = []     # a board-only project; the v2.0 project keeps its sheet
    r = pro["board"]["design_settings"]["rules"]
    r.update(min_clearance=RULES["clearance"], min_track_width=RULES["track"], min_via_diameter=RULES["via"],
             min_through_hole_diameter=RULES["via_drill"], min_via_annular_width=RULES["annular"],
             min_copper_edge_clearance=RULES["edge"], min_hole_to_hole=RULES["hole_to_hole"],
             min_hole_clearance=RULES["hole_clearance"])
    ds = pro["board"]["design_settings"]
    ds["track_widths"] = [0.0, RULES["track"]]
    ds["via_dimensions"] = [{"diameter": 0.0, "drill": 0.0}, {"diameter": RULES["via"], "drill": RULES["via_drill"]}]
    base = pro["net_settings"]["classes"][0]
    base.update(track_width=RULES["track"], clearance=RULES["clearance"], via_diameter=RULES["via"],
                via_drill=RULES["via_drill"])
    power = dict(base, name="Power", priority=0, track_width=0.4)
    pro["net_settings"]["classes"] = [base, power]
    pro["net_settings"]["netclass_patterns"] = [{"netclass": "Power", "pattern": "GND"},
                                                {"netclass": "Power", "pattern": "VCC"}]
    json.dump(pro, open(out + ".kicad_pro", "w"), indent=2)
    open(out + ".kicad_dru", "w").write(DRU)


# ---------------------------------------------------------------------------------------------------------------------
# board
def place_fp(fp, spec, pcbnew):
    """put a footprint where relayout_placements.py says: rotation, pad-bbox centre, pad 1 snapped to the X1 grid"""
    cx, cy, o = spec
    if isinstance(o, str):
        deg = RP.DIP_ROT[o] + (90 if fp.GetFPIDAsString().startswith("Package_DIP") else 0)
    else:
        deg = o
    FM, T = pcbnew.FromMM, pcbnew.ToMM
    fp.SetOrientationDegrees(deg % 360)
    fp.SetPosition(pcbnew.VECTOR2I(0, 0))
    pads = list(fp.Pads())
    xs = [T(p.GetPosition().x) for p in pads]
    ys = [T(p.GetPosition().y) for p in pads]
    ox, oy = cx - (min(xs) + max(xs)) / 2, cy - (min(ys) + max(ys)) / 2
    p1 = [p for p in pads if p.GetNumber() in ("1", "A")] or pads
    px, py = T(p1[0].GetPosition().x) + ox, T(p1[0].GetPosition().y) + oy
    gx, gy = RP.GRID_ORIGIN
    ox += round((px - gx) / RP.GRID) * RP.GRID + gx - px
    oy += round((py - gy) / RP.GRID) * RP.GRID + gy - py
    fp.SetPosition(pcbnew.VECTOR2I(FM(ox), FM(oy)))


def build(opt, netfile, out=None):
    import pcbnew
    from pcbnew import VECTOR2I
    O = RP.OPTIONS[opt]
    FM = pcbnew.FromMM
    P = lambda x, y: VECTOR2I(FM(x), FM(y))
    nodes, paths = GM.read_netlist(netfile)
    out = out or fname(opt)
    src = open(os.path.join(GM.V13, GM.OLD + ".kicad_pcb")).read()
    assert src.count('"%s"' % GM.TITLE_OLD) == 1
    src = src.replace('"%s"' % GM.TITLE_OLD, '"%s"' % GM.TITLE_NEW)
    forms = gen_cf.top_forms(src)
    kept = [f for f in forms if not re.match(r"\((segment|via|arc)\b", f)]
    dropped = len(forms) - len(kept)
    open(out, "w").write("(kicad_pcb\n\t" + "\n\t".join(kept) + "\n)\n")
    b = pcbnew.LoadBoard(out)
    fps = {f.GetReference(): f for f in b.GetFootprints()}
    x1_at = (fps["X1"].GetPosition().x, fps["X1"].GetPosition().y, fps["X1"].GetOrientationDegrees())
    old_at = {r: (f.GetPosition().x, f.GetPosition().y) for r, f in fps.items()}

    nets = {}

    def net(name):
        if name not in nets:
            ni = b.FindNet(name)
            if ni is None:
                ni = pcbnew.NETINFO_ITEM(b, name)
                b.Add(ni)
            nets[name] = ni
        return nets[name]

    for ref, (value, symid, fpid, note) in NL.PARTS.items():
        lib, name = fpid.split(":")
        fp = pcbnew.FootprintLoad(os.path.join(GM.KFP, lib + ".pretty"), name)
        if fp is None:
            raise SystemExit("board: footprint %s not found" % fpid)
        fp.SetFPIDAsString(fpid)
        fp.SetReference(ref)
        fp.SetValue(value)
        fp.SetField("Description", note)
        b.Add(fp)
        fps[ref] = fp
    for ref, fp in fps.items():
        if ref in NL.REMOVED:
            # C20-C23: removed from the schematic after these option boards were made (Ken 2026-09-24); the option
            # boards are the review record from before, so they keep them as the built board has them (path, GND /
            # VCC pads); finish_v2.py make takes them off the final board
            got = {p.GetNumber(): p.GetNetname() for p in fp.Pads()}
            if got != NL.REMOVED_NETS:
                raise SystemExit("board: removed part %s has pads %s on the built board" % (ref, got))
            continue
        if ref not in paths:
            raise SystemExit("board: %s is not in the schematic" % ref)
        fp.SetPath(pcbnew.KIID_PATH("/" + "/".join(x for x in paths[ref].split("/") if x and x != GM.ROOT_UUID)))
        for p in fp.Pads():
            if p.GetNumber() == "":
                continue
            if (ref, p.GetNumber()) in nodes:
                p.SetNet(net(nodes[(ref, p.GetNumber())]))
            elif p.GetNetname():
                raise SystemExit("board: %s.%s is on %s but has no pin in the schematic" % (ref, p.GetNumber(),
                                                                                            p.GetNetname()))
    missing = sorted(r for r in fps if r != "X1" and r not in O["place"])
    extra = sorted(r for r in O["place"] if r not in fps)
    if missing or extra:
        raise SystemExit("option %s: parts not placed %s, unknown %s" % (opt, missing, extra))
    if "X1" in O["place"]:
        raise SystemExit("option %s: X1 stays where the built card has it" % opt)
    for ref, spec in O["place"].items():
        place_fp(fps[ref], spec, pcbnew)
    # reference texts of the KiCad-library parts: small, beside the body (the Eagle parts keep theirs)
    for ref in NL.PARTS:
        fp = fps[ref]
        fld = fp.Reference()
        fld.SetTextSize(VECTOR2I(FM(1.0), FM(1.0)))
        fld.SetTextThickness(FM(0.15))
    # the built card's silkscreen labels that belong to a part move with it
    delta = {r: (fps[r].GetPosition().x - old_at[r][0], fps[r].GetPosition().y - old_at[r][1]) for r in old_at}
    LABELS = {"ROM": "U$1", "RAM": "U$1", "0X8000": "U$1", "0XF000": "U$1", "-BUS-EN": "JP1", "Gnd": "JP1"}
    for d in b.GetDrawings():
        if d.GetClass() != "PCB_TEXT":
            continue
        t = d.GetText()
        if t in LABELS:
            dx, dy = delta[LABELS[t]]
            d.SetPosition(VECTOR2I(d.GetPosition().x + dx, d.GetPosition().y + dy))
        elif t in O.get("texts", {}):
            d.SetPosition(P(*O["texts"][t]))

    def text(s, x, y, size=1.0, angle=0, layer=pcbnew.F_SilkS, just=pcbnew.GR_TEXT_H_ALIGN_LEFT):
        t = pcbnew.PCB_TEXT(b)
        t.SetText(s)
        t.SetLayer(layer)
        t.SetTextSize(VECTOR2I(FM(size), FM(size)))
        t.SetTextThickness(FM(max(0.15, size * 0.15)))
        t.SetHorizJustify(just)
        t.SetTextAngleDegrees(angle)
        t.SetPosition(P(x, y))
        b.Add(t)

    def rect(x0, y0, x1, y1, layer, dash=False, w=0.2):
        for (a, c, d_, e) in ((x0, y0, x1, y0), (x1, y0, x1, y1), (x1, y1, x0, y1), (x0, y1, x0, y0)):
            s = pcbnew.PCB_SHAPE(b)
            s.SetShape(pcbnew.SHAPE_T_SEGMENT)
            s.SetStart(P(a, c))
            s.SetEnd(P(d_, e))
            s.SetLayer(layer)
            s.SetWidth(FM(0.301 if dash else w))
            b.Add(s)

    JUST = {"l": pcbnew.GR_TEXT_H_ALIGN_LEFT, "c": pcbnew.GR_TEXT_H_ALIGN_CENTER, "r": pcbnew.GR_TEXT_H_ALIGN_RIGHT}
    for s, x, y, size, angle, just in O.get("silk", []):
        text(s, x, y, size, angle, just=JUST[just])
    # the TAODAN adapter (User.Drawings): strip + keep-low zone, from J2's pads
    j2 = fps["J2"]
    ys = sorted(pcbnew.ToMM(p.GetPosition().y) for p in j2.Pads())
    xs = sorted(pcbnew.ToMM(p.GetPosition().x) for p in j2.Pads())
    c = (xs[0] + xs[-1]) / 2
    m = (ys[0] + ys[-1]) / 2
    keep = (c - RP.LOW_SIDE, ys[0] - RP.LOW_BEYOND, c + RP.LOW_SIDE, ys[-1] + RP.LOW_BEYOND)
    rect(*keep, pcbnew.Dwgs_User, dash=True)
    rect(c - 4.0, m - RP.TAODAN_LEN / 2, c + 4.0, m + RP.TAODAN_LEN / 2, pcbnew.Dwgs_User, w=0.3)
    text("Option %s: %s" % (opt.upper(), O["title"]), 20.0, 7.0, 1.5, 0, pcbnew.Dwgs_User)
    text("Solid: TAODAN CF-IDE40 on J2 (70 mm, standing up); dashed: keep-low zone (nothing over ~8 mm)",
         20.0, 128.0, 1.2, 0, pcbnew.Dwgs_User)
    # planes: thermal reliefs and antipads of the re-layout rules
    for z in b.Zones():
        if z.GetIsRuleArea() or z.GetNetname() not in ("GND", "VCC"):
            continue
        z.SetLocalClearance(FM(RULES["plane_clearance"]))
        z.SetThermalReliefGap(FM(RULES["thermal_gap"]))
        z.SetThermalReliefSpokeWidth(FM(RULES["thermal_spoke"]))
        z.SetPadConnection(pcbnew.ZONE_CONNECTION_THERMAL)
    fx = fps["X1"]
    assert (fx.GetPosition().x, fx.GetPosition().y, fx.GetOrientationDegrees()) == x1_at
    pcbnew.SaveBoard(out, b)
    t = open(out).read()
    t = re.sub(r"\(width 0\.301\)(\s*)\(type (?:solid|default)\)", r"(width 0.3)\1(type dash)", t)
    open(out, "w").write(t)
    write_project(opt)
    print("board %s: %d footprints (%d placed, X1 kept), %d built copper items removed"
          % (os.path.basename(out), len(fps), len(O["place"]), dropped))


# ---------------------------------------------------------------------------------------------------------------------
# checks
TALL = GM.TALL             # parts taller than ~8 mm (LEDs, headers + shunts, the radial cap, X1)


def check(pcb, opt):
    """no body overlaps (courtyards; the Eagle parts: pads + silk/fab graphics), every pad 0.5 mm inside the edge, X1 on
    its built spot, nothing tall (TALL) and no IC in the TAODAN keep-low zone; reference texts of the parts clear of
    every pad"""
    import pcbnew
    b = pcbnew.LoadBoard(pcb)
    T = pcbnew.ToMM
    boxes = GM.body_boxes(b)
    probs = []
    refs = sorted(boxes)
    for i, a in enumerate(refs):
        for c in refs[i + 1:]:
            o = GM.overlap(boxes[a], boxes[c])
            if o:
                probs.append("%s / %s overlap %.2f x %.2f mm" % (a, c, o[0], o[1]))
    E = b.GetBoardEdgesBoundingBox()
    ex0, ey0, ex1, ey1 = T(E.GetX()), T(E.GetY()), T(E.GetRight()), T(E.GetBottom())
    pads = []
    for f in b.GetFootprints():
        ref = f.GetReference()
        for p in f.Pads():
            pb = p.GetBoundingBox()
            pads.append((ref, p.GetNumber(), pb))
            if ref == "X1":
                continue
            x0, y0, x1, y1 = T(pb.GetX()), T(pb.GetY()), T(pb.GetRight()), T(pb.GetBottom())
            if min(x0 - ex0, y0 - ey0, ex1 - x1, ey1 - y1) < 0.5:
                probs.append("%s pad %s within 0.5 mm of the board edge" % (ref, p.GetNumber()))
        bx = boxes[ref]
        if ref != "X1" and (bx[0] < ex0 or bx[1] < ey0 or bx[2] > ex1 + 0.01 or bx[3] > ey1):
            probs.append("%s body outside the board outline %s" % (ref, [round(v, 2) for v in bx]))
    # X1 exactly where the built card has it
    import re as _re
    built = open(os.path.join(GM.V13, GM.OLD + ".kicad_pcb")).read()
    m = _re.search(r'\(footprint "[^"]*FABC96R"[^\n]*\n(?:[^\n]*\n){0,6}?\s*\(at ([-\d.]+) ([-\d.]+)(?: ([-\d.]+))?\)', built)
    fx = [f for f in b.GetFootprints() if f.GetReference() == "X1"][0]
    if m and (abs(float(m.group(1)) - T(fx.GetPosition().x)) > 1e-3 or abs(float(m.group(2)) - T(fx.GetPosition().y)) > 1e-3):
        probs.append("X1 moved")
    # keep-low zone of the adapter
    j2 = [f for f in b.GetFootprints() if f.GetReference() == "J2"][0]
    ys = sorted(T(p.GetPosition().y) for p in j2.Pads())
    xs = sorted(T(p.GetPosition().x) for p in j2.Pads())
    c = (xs[0] + xs[-1]) / 2
    keep = (c - RP.LOW_SIDE, ys[0] - RP.LOW_BEYOND, c + RP.LOW_SIDE, ys[-1] + RP.LOW_BEYOND)
    under = sorted(r for r, bx in boxes.items() if r != "J2" and GM.overlap(bx, keep))
    for r in under:
        if r in TALL or r.startswith("IC"):
            probs.append("%s in the TAODAN keep-low zone" % r)
    near = []
    for r in list(TALL) + [r for r in boxes if r.startswith("IC")]:
        if r in boxes and r != "J2":
            bx = boxes[r]
            dx = max(keep[0] - bx[2], bx[0] - keep[2], 0)
            dy = max(keep[1] - bx[3], bx[1] - keep[3], 0)
            near.append((round((dx * dx + dy * dy) ** 0.5, 1), r))
    # reference texts on pads
    onpad = []
    for f in b.GetFootprints():
        fld = f.Reference()
        if not fld.IsVisible():
            continue
        tb = fld.GetBoundingBox()
        for ref, num, pb in pads:
            if tb.Intersects(pb):
                onpad.append("%s on %s.%s" % (f.GetReference(), ref, num))
                break
    print("placement %s: %s" % (os.path.basename(pcb), "OK - no overlaps, pads 0.5 mm inside the edge, X1 as built, "
                                "keep-low zone clear of ICs and tall parts" if not probs else "%d problem(s)" % len(probs)))
    for x in probs:
        print("    ", x)
    print("    J2 pads x %.2f/%.2f, y %.2f-%.2f; keep-low zone x %.1f-%.1f, y %.1f-%.1f holds: %s"
          % (xs[0], xs[-1], ys[0], ys[-1], keep[0], keep[2], keep[1], keep[3], ", ".join(under) or "nothing"))
    print("    nearest tall parts / ICs to the keep-low zone: %s" % ", ".join("%s %.1f mm" % (r, d) for d, r in sorted(near)[:4]))
    print("    reference texts touching a pad: %d %s" % (len(onpad), onpad[:8]))
    return not probs


def airwire(pcb):
    """straight-line length of the signal nets' minimum spanning trees (GND/VCC excluded: planes), mm"""
    import pcbnew
    b = pcbnew.LoadBoard(pcb)
    T = pcbnew.ToMM
    pts = collections.defaultdict(list)
    for f in b.GetFootprints():
        for p in f.Pads():
            n = p.GetNetname()
            if n and n not in ("GND", "VCC") and not n.startswith("unconnected-("):
                pts[n].append((T(p.GetPosition().x), T(p.GetPosition().y)))
    tot, conns = 0.0, 0
    for n, ps in pts.items():
        if len(ps) < 2:
            continue
        inn, rest = [ps[0]], ps[1:]
        while rest:
            d, j = min((math.dist(a, c), j) for j, c in enumerate(rest) for a in inn)
            tot += d
            conns += 1
            inn.append(rest.pop(j))
    return tot, conns, len([n for n, ps in pts.items() if len(ps) >= 2])


# ---------------------------------------------------------------------------------------------------------------------
# trial autoroute
def dsn(pcb, out):
    """a two-signal-layer copy (the plane zones dropped, the inner layers removed) -> Specctra DSN for Freerouting; the
    routing boundary inset 0.35 mm (Freerouting's own edge clearance + 0.35 = the 0.5 mm rule)"""
    import pcbnew
    sys.path.insert(0, os.path.join(GM.ROOT, "tools", "kicad"))
    import kicad_route as KR
    t = open(pcb).read()
    forms = gen_cf.top_forms(t)
    keep = [f for f in forms if not (f.startswith("(zone") and "(keepout" not in f)]
    d = os.path.dirname(os.path.abspath(out))
    tmp = os.path.join(d, "_dsn2l.kicad_pcb")
    open(tmp, "w").write("(kicad_pcb\n\t" + "\n\t".join(keep) + "\n)\n")
    pro = pcb[:-len(".kicad_pcb")] + ".kicad_pro"
    import shutil
    shutil.copy(pro, os.path.join(d, "_dsn2l.kicad_pro"))
    try:
        b = pcbnew.LoadBoard(tmp)
        b.SetCopperLayerCount(2)
        if not pcbnew.ExportSpecctraDSN(b, out):
            raise SystemExit("dsn: export failed")
    finally:
        for f in ("_dsn2l.kicad_pcb", "_dsn2l.kicad_pro", "_dsn2l.kicad_prl"):
            if os.path.exists(os.path.join(d, f)):
                os.remove(os.path.join(d, f))
    s = KR._inset_dsn_boundary(open(out).read())
    open(out, "w").write(s)
    layers = re.findall(r"\(layer (\S+)\s*\(type (\w+)\)", s)
    classes = re.findall(r"\(class (\S+)", s)
    print("dsn %s: layers %s, classes %s" % (os.path.basename(out), layers, classes))


def ses(pcb, sesfile, out):
    import pcbnew
    import shutil
    shutil.copy(pcb, out)
    b = pcbnew.LoadBoard(out)
    if not pcbnew.ImportSpecctraSES(b, sesfile):
        raise SystemExit("ses: ImportSpecctraSES failed")
    pcbnew.SaveBoard(out, b)
    ntrk = sum(1 for t in b.GetTracks() if t.Type() == pcbnew.PCB_TRACE_T)
    nvia = sum(1 for t in b.GetTracks() if t.Type() == pcbnew.PCB_VIA_T)
    # the session's F.Cu-B.Cu vias come in as "buried" on the 4-layer board: they are through vias (fixed
    # 2026-09-24; the three committed trial routes of 2cae926 still carry the buried type, finish_v2.py make fixes it)
    t = open(out).read()
    nb = len(re.findall(r"^\t\(via (?:buried|blind)\b", t, re.M))
    open(out, "w").write(re.sub(r"^\t\(via (?:buried|blind)\b", "\t(via", t, flags=re.M))
    print("ses -> %s: %d track segments, %d vias (%d imported as buried -> through)" % (os.path.basename(out), ntrk,
                                                                                      nvia, nb))


COSMETIC = {"silk_overlap", "silk_edge_clearance", "silk_over_copper", "text_height", "text_thickness",
            "lib_footprint_mismatch", "lib_footprint_issues", "courtyards_overlap", "missing_courtyard"}


def stats(pcb, drcfile, opt=None):
    import pcbnew
    b = pcbnew.LoadBoard(pcb)
    T = pcbnew.ToMM
    L = collections.Counter()
    nvia = 0
    widths = collections.Counter()
    for t in b.GetTracks():
        if t.Type() == pcbnew.PCB_VIA_T:
            nvia += 1
        else:
            L[b.GetLayerName(t.GetLayer())] += T(t.GetLength())
            widths[round(T(t.GetWidth()), 3)] += 1
    d = json.load(open(drcfile))
    # X1's two mounting holes sit inside X1's own via keepout (the converted Eagle footprint): the built card's DRC
    # has the same two items; they are not copper
    x1 = lambda v: v["type"] == "items_not_allowed" and all(" of X1" in i["description"] for i in v["items"])
    inherited = sum(1 for v in d["violations"] if x1(v))
    c = collections.Counter(v["type"] for v in d["violations"] if not x1(v))
    copper = {k: n for k, n in c.items() if k not in COSMETIC}
    unr = len(d.get("unconnected_items", []))
    aw, conns, nn = airwire(pcb)
    print("trial route %s:\n  unrouted connections after Freerouting: %d\n  vias: %d\n  track length: %.0f mm "
          "(F.Cu %.0f, B.Cu %.0f; placement airwire %.0f mm over %d connections)\n  track widths (mm: segments): %s\n"
          "  DRC copper violations: %s\n  DRC inherited: %d (X1's mounting holes in X1's own keepout, as on the built "
          "card)\n  DRC cosmetic (silkscreen, Eagle library texts): %s"
          % (os.path.basename(pcb), unr, nvia, sum(L.values()), L.get("F.Cu", 0), L.get("B.Cu", 0), aw, conns,
             dict(widths), copper or "none", inherited, dict(sorted((k, n) for k, n in c.items() if k in COSMETIC))))
    for u in d.get("unconnected_items", []):
        print("    unrouted: %s" % " - ".join(i["description"] for i in u["items"]))
    return dict(unrouted=unr, vias=nvia, length=round(sum(L.values())), copper=copper)


if __name__ == "__main__":
    cmd = sys.argv[1]
    if cmd == "board":
        build(sys.argv[2], sys.argv[3], sys.argv[4] if len(sys.argv) > 4 else None)
    elif cmd == "refill":
        GM.refill(sys.argv[2])
    elif cmd == "check":
        ok = check(sys.argv[2], sys.argv[3])
        sys.stdout.flush()
        os._exit(0 if ok else 1)
    elif cmd == "airwire":
        tot, conns, nn = airwire(sys.argv[2])
        print("airwire %s: %.0f mm, %d connections on %d signal nets" % (os.path.basename(sys.argv[2]), tot, conns, nn))
    elif cmd == "review":
        GM.review_copy(sys.argv[2], sys.argv[3], sys.argv[4])
    elif cmd == "dsn":
        dsn(sys.argv[2], sys.argv[3])
    elif cmd == "ses":
        ses(sys.argv[2], sys.argv[3], sys.argv[4])
    elif cmd == "stats":
        stats(sys.argv[2], sys.argv[3], sys.argv[4] if len(sys.argv) > 4 else None)
    sys.stdout.flush()
    os._exit(0)
