#!/usr/bin/env python3
# Author: Claude (Anthropic) for Ken Rother's YACC1 project, 2026
"""author_headers.py - the authorship line at the top of every source file (Ken, 2026-10-02).

Every source file in the tree says at its top who wrote it, in a short comment block:

    Author: Ken Rother (original)                                       Ken's code, unchanged
    Author: Ken Rother (original)                                       Ken's code that Claude changed; every change
    Changes: Claude (Anthropic), 2026 - see tools/patched_files.txt       is listed in tools/patched_files.txt
    Author: Ken Rother (original: <what>)                               a copy of Ken's code that Claude reworked
    Changes: Claude (Anthropic), 2026 - see git history                   under a new name (Sequencer4)
    Author: Claude (Anthropic) for Ken Rother's YACC1 project, 2026     written in YACC1-D
    Author: Claude (Anthropic), 2026 - ported from Ken Rother's P8X project   a Y1/OS command or library ported
                                                                        from P8X (os/PORT-PLAN.md)
    Author: Michael H. Riley (RC/asm 2.2); YACC1 port: Ken Rother       software/assembler (+ the Changes line
                                                                        where Claude changed it)

tools/authors.tsv holds each file's category and why (path, category, note); this script made it on 2026-10-02
from the tree's own records and it is the authority from then on (edit a line to correct a file). Left alone:
third-party code (it keeps its own licence header), generated files (their generator's "GENERATED by" line says
where they come from), NetBeans' own nbproject/ makefiles, and the frozen archive/ and deprecated/ folders.

    python3 tools/author_headers.py --classify   (re)write tools/authors.tsv for files not in it yet
    python3 tools/author_headers.py --apply      put the header on every file that lacks it or has a stale one
    python3 tools/author_headers.py --check      exit 1 if a source file has no header or the wrong one, or is not
                                                 in tools/authors.tsv (make check runs this)
A new source file: add a line to tools/authors.tsv (a file Claude writes: category "claude") and run --apply.
"""
import csv, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLE = os.path.join(ROOT, "tools/authors.tsv")
EXT = {".c", ".h", ".cpp", ".ino", ".pde", ".py", ".sh", ".mk", ".asm", ".inc"}
SKIP_DIRS = ("archive/", "migration/", "vm/", "media/")
THIRD_PARTY = ("embedded/libraries/Adafruit_MCP23017_Arduino_Library/", "embedded/libraries/extEEPROM/",
               "os/upstream/", "software/ubasic-c/", "software/assembler/upstream/")
THIRD_PARTY_FILES = {"os/commands/kermit.c": "E-Kermit 1.8 (Columbia University) adapted by Claude; its licence header stays"}
GENERATED = {"os/asm_optab.c", "os/dis_optab.c", "os/kermit_io.c", "os/commands-asm/asmtab.inc"}
# os/PORT-PLAN.md sections 2 and 8: the P8X commands and shared libraries ported to Y1/OS (waves 0-2, vi)
P8X = {"os/commands/%s.c" % n for n in ("pwd help dep dump examine cat wc head tail more sort uniq sed awk cmp diff "
                                        "man md touch del mv cp dir find tree grep vi").split()} | \
      {"os/lib_%s.c" % n for n in "stdin rdline glob globx regex walk apath more num err".split()}
# RC/asm 2.2 (Michael H. Riley) as Ken ported it to YACC1 (software/assembler/README.md); upstream/ is the unmodified 2.2
RCASM = "software/assembler/"
# files the YACCS records list but Claude wrote: the plain Makefiles that replaced the NetBeans ones (each says so in
# its first line), and the KiCad pilot's tools (done in YACCS by Claude, 2026-09)
OVERRIDE = {f: ("claude", "written by Claude (from YACCS records, but Claude's)") for f in (
    "firmware/microcode/ucode-generator2/Makefile", "software/assembler/Makefile", "software/disassembler/disasm2/Makefile")}
# copies of Ken's code that Claude reworked under a new name (the file's own first lines say so)
KEN_DERIVED = {p: "Sequencer3 2021-08 + IO.ino 2024-07" for p in (
    "embedded/sequencer-card/sequencer4/Sequencer4.ino", "embedded/sequencer-card/sequencer4/IO.ino",
    "embedded/sequencer-card/sequencer4/download.ino", "embedded/sequencer-card/sequencer4/uCodeRAM.ino",
    "embedded/sequencer-card/sequencer4/uCodeROM.ino", "embedded/sequencer-card/sequencer4/YACC_Common_headera.h")}

LINES = {
    "ken": ["Author: Ken Rother (original)"],
    "ken+claude": ["Author: Ken Rother (original)", "Changes: Claude (Anthropic), 2026 - see tools/patched_files.txt"],
    "ken-derived": ["Author: Ken Rother (original: {note})", "Changes: Claude (Anthropic), 2026 - see git history"],
    "claude": ["Author: Claude (Anthropic) for Ken Rother's YACC1 project, 2026"],
    "claude-p8x": ["Author: Claude (Anthropic), 2026 - ported from Ken Rother's P8X project"],
    "rcasm": ["Author: Michael H. Riley (RC/asm 2.2); YACC1 port: Ken Rother"],
    "rcasm+claude": ["Author: Michael H. Riley (RC/asm 2.2); YACC1 port: Ken Rother",
                     "Changes: Claude (Anthropic), 2026 - see tools/patched_files.txt"],
}
HEADED = ("ken", "ken+claude", "ken-derived", "claude", "claude-p8x", "rcasm", "rcasm+claude")


def git_files():
    return [f for f in subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True).stdout.split("\n") if f]


def is_source(f):
    b, e = os.path.basename(f), os.path.splitext(f)[1].lower()
    if f.startswith(SKIP_DIRS) or "/deprecated/" in f or "/nbproject/" in f: return False
    if os.path.islink(os.path.join(ROOT, f)): return False       # layout links (tools/layout_links.py): the target has the header
    return e in EXT or b in ("Makefile", "makefile")


def style(f):
    e = os.path.splitext(f)[1].lower()
    if e in (".asm", ".inc"): return "asm"
    if e in (".py", ".sh", ".mk") or os.path.basename(f) in ("Makefile", "makefile"): return "hash"
    return "c"


def block(f, cat, note):
    lines = [l.format(note=note) for l in LINES[cat]]
    s = style(f)
    if s == "asm": return "".join("; %s\n" % l for l in lines)
    if s == "hash": return "".join("# %s\n" % l for l in lines)
    return "/*\n" + "".join(" * %s\n" % l for l in lines) + " */\n"


HEADER_RE = re.compile(r"^(?:/\*\n(?: \* (?:Author|Changes): [^\n]*\n)+ \*/\n|(?:; (?:Author|Changes): [^\n]*\n)+|(?:# (?:Author|Changes): [^\n]*\n)+)")


def split_head(text):
    """(prefix that must stay first: shebang / coding line, rest)"""
    pre = ""
    if text.startswith("#!"):
        i = text.index("\n") + 1; pre, text = text[:i], text[i:]
        if re.match(r"#.*coding[:=]", text):
            i = text.index("\n") + 1; pre, text = pre + text[:i], text[i:]
    return pre, text


def classify():
    plan = {r["destination"]: r["mode"] for r in csv.DictReader(open(os.path.join(ROOT, "migration/dryrun-plan.tsv")), delimiter="\t")}
    logged = set()
    import glob
    for lf in glob.glob(os.path.join(ROOT, "migration/run-log-*.tsv")):
        for r in csv.DictReader(open(lf), delimiter="\t"):
            if r["result"] in ("copied", "already", "clash"): logged.add(r["destination"])
    patched = {l.split("\t")[0].strip() for l in open(os.path.join(ROOT, "tools/patched_files.txt")) if "\t" in l and not l.startswith("#")}
    rows = []
    for f in git_files():
        if not is_source(f): continue
        if f.startswith(THIRD_PARTY): rows.append((f, "third-party", "kept as published, with its own licence header")); continue
        if f in THIRD_PARTY_FILES: rows.append((f, "third-party", THIRD_PARTY_FILES[f])); continue
        if f in GENERATED: rows.append((f, "generated", "its generator's GENERATED line says where it comes from")); continue
        if f in KEN_DERIVED: rows.append((f, "ken-derived", KEN_DERIVED[f])); continue
        if f in OVERRIDE or f.startswith("tools/kicad/"): rows.append((f, "claude", "Claude's (the YACCS records list it: the KiCad pilot / a plain Makefile)")); continue
        if f.startswith(RCASM) and os.path.dirname(f) == "software/assembler" and os.path.splitext(f)[1] in (".c", ".h"):
            rows.append((f, "rcasm+claude" if f in patched else "rcasm", "RC/asm 2.2 (Michael H. Riley), Ken's YACC1 port")); continue
        from_yaccs = plan.get(f) in ("copy", "archive") or f in logged
        if from_yaccs and f in patched: rows.append((f, "ken+claude", "from YACCS; Claude's changes in tools/patched_files.txt")); continue
        if from_yaccs: rows.append((f, "ken", "from YACCS (migration/ plan or run log)")); continue
        if f in P8X: rows.append((f, "claude-p8x", "os/PORT-PLAN.md: ported from P8X")); continue
        rows.append((f, "claude", "written in YACC1-D"))
    return rows


def load_table():
    return {r[0]: (r[1], r[2] if len(r) > 2 else "") for r in csv.reader(open(TABLE), delimiter="\t") if r and not r[0].startswith("#")}


def write_table(rows):
    with open(TABLE, "w", newline="") as fh:
        fh.write("# tools/authors.tsv - who wrote each source file (tools/author_headers.py; Ken 2026-10-02). Columns: path,\n"
                 "# category (ken / ken+claude / ken-derived / claude / claude-p8x get a header; third-party / generated do not),\n"
                 "# note (for ken-derived: what it was made from). Edit a line to correct a file, then --apply.\n")
        w = csv.writer(fh, delimiter="\t", lineterminator="\n")
        for r in sorted(rows): w.writerow(r)


def main():
    a = sys.argv[1:]
    if "--classify" in a:
        old = load_table() if os.path.exists(TABLE) else {}
        rows = [(f, *old[f]) if f in old else (f, c, n) for f, c, n in classify()]
        write_table(rows)
        cats = {}
        for _, c, _ in rows: cats[c] = cats.get(c, 0) + 1
        print("authors.tsv: %d source files %s" % (len(rows), cats)); return 0
    table = load_table(); problems = []; changed = 0
    for f in git_files():
        if not is_source(f): continue
        if f not in table: problems.append("%s: not in tools/authors.tsv" % f); continue
        cat, note = table[f]
        if cat not in HEADED: continue
        p = os.path.join(ROOT, f); text = open(p, encoding="utf-8", errors="surrogateescape").read()
        pre, rest = split_head(text)
        want = block(f, cat, note)
        m = HEADER_RE.match(rest)
        have = m.group(0) if m else None
        if have == want: continue
        if "--apply" in a:
            body = rest[m.end():] if m else rest
            body = body.lstrip("\n") if m else body
            sep = "" if body.startswith("\n") else "\n"
            open(p, "w", encoding="utf-8", errors="surrogateescape").write(pre + want + sep + body); changed += 1
        else:
            problems.append("%s: %s" % (f, "header missing" if not have else "header differs from tools/authors.tsv (%s)" % cat))
    if "--apply" in a: print("author headers: %d file(s) written" % changed)
    for p in problems[:40]: print("  " + p)
    print("author headers: %s" % ("PASS" if not problems else "FAIL (%d)" % len(problems)))
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
