#!/usr/bin/env python3
"""Regenerate hardware/FABRICATED.md and the FABRICATED marker file in every fabricated revision folder
from tools/fabricated.py. Run from the repo root. Removes stale markers first."""
import os, sys, time, collections
sys.path.insert(0, os.path.dirname(__file__)); from fabricated import FABRICATED
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))); HW = os.path.join(ROOT, "hardware")
for root, dirs, files in os.walk(HW):
    if "FABRICATED" in files: os.remove(os.path.join(root, "FABRICATED"))
missing = []
for card, folder, rev, status, confirmed, note in FABRICATED:
    d = os.path.join(HW, folder)
    if not os.path.isdir(d): missing.append(folder); continue
    if status in ("in-machine", "fabricated"):
        with open(os.path.join(d, "FABRICATED"), "w") as f:
            f.write("card: %s\nrevision: %s\nstatus: %s\nconfirmed: %s\nnote: %s\n(generated by tools/gen_fabricated.py from tools/fabricated.py - edit the table, not this file)\n"
                    % (card, rev, status, confirmed or "-", note))
by_card = collections.OrderedDict()
for row in FABRICATED: by_card.setdefault(row[0], []).append(row)
order = ["in-machine", "fabricated", "edits", "design-only"]
with open(os.path.join(HW, "FABRICATED.md"), "w") as f:
    f.write("# Fabricated boards\n\nGenerated %s by `tools/gen_fabricated.py` from `tools/fabricated.py` (edit the table, then re-run).\n"
            "Every revision folder under `hardware/` is listed; the ones with status **in-machine** or **fabricated** also carry a `FABRICATED` marker file.\n"
            "\"presumed\" means the only evidence is that the folder sat in `PCB/Production` in the old tree.\n"
            "Fabrication output (gerber zips, CAM jobs, drill/photoplotter logs, order invoices) lives in `hardware/fab/<card>/<rev>/`; "
            "the Eagle folder keeps only the design. Where the tree holds no fab output the board was most likely ordered by uploading "
            "the `.brd` straight to OSH Park, so the `.brd` in the design folder IS what was sent.\n\n" % time.strftime("%Y-%m-%d"))
    def fab_of(folder):
        d = os.path.join(HW, folder, "fab")
        if not os.path.isdir(d): return "**none in tree**"
        zips = sorted(x for x in os.listdir(d) if x.lower().endswith((".zip", ".pdf")))
        cam = os.path.isdir(os.path.join(d, "CAMOutputs")); ger = os.path.isdir(os.path.join(d, "gerbers"))
        what = ", ".join(zips + (["CAMOutputs/"] if cam else []) + (["gerbers/"] if ger else [])) or "(files)"
        return "`%s/fab/` %s" % (folder, what)
    f.write("## In the machine\n\n| Card | Revision | Design | Files sent to fab | Confirmed by | Note |\n|---|---|---|---|---|---|\n")
    for card, folder, rev, status, confirmed, note in FABRICATED:
        if status == "in-machine": f.write("| %s | %s | `%s` | %s | %s | %s |\n" % (card, rev, folder, fab_of(folder), confirmed, note))
    f.write("\n## Every revision, by card\n\n")
    for card, rows in by_card.items():
        f.write("### %s\n\n| Revision | Status | Design | Files sent to fab | Note |\n|---|---|---|---|---|\n" % card)
        for c, folder, rev, status, confirmed, note in sorted(rows, key=lambda r: order.index(r[3])):
            f.write("| %s | %s | `%s` | %s | %s |\n" % (rev, status + (" (%s)" % confirmed if confirmed else ""), folder,
                    fab_of(folder) if status in ("in-machine", "fabricated") else "-", note))
        f.write("\n")
print("markers written; folders in the table but not on disk:", missing or "none")
