#!/usr/bin/env python3
"""Mechanical review of the microcode of every opcode, from test.hex + the signal table, using what the hardware does:
   - the pipeline registers apply a step's control word for the whole step; a bus write happens while -MEM-WR (or
     -IO-WR) is low, so the ADDRESS and the DATA must not change while it is asserted (a change = a glitch write to
     another location, exactly the class of fault a slow TTL bus turns into corrupted memory)
   - the address bus is driven by the register selected by ADDR-REG-ID; -REG-UP/-REG-DN (with -REG-FUNC-RD) change the
     register selected by REG-RD-ID; REG-LD-LO/HI (with -REG-FUNC-LD) load the register selected by REG-LD-ID from the
     data bus; the data bus is driven by whichever of -AC-RD / -REG-RD-LO/HI / -TMP-REG-RD0/1 / -BRANCH-RD / -MEM-RD /
     -IO-RD is asserted
   - the memory card ignores the bus unless -VMA is asserted (with -BUS-EN)
   - an instruction ends at the step that asserts UCODE-COUNT-RESET; without it the counter runs to step 63
Checks per opcode/step:
   W1  -MEM-WR/-IO-WR asserted while the address changes (source register changes, is incremented/decremented, or is
       loaded) between this step and the previous or next asserted step
   W2  -MEM-WR/-IO-WR asserted with nothing driving the data bus, or with the data source changing while asserted
   W3  -MEM-WR asserted without -VMA; -MEM-RD without -VMA
   R1  -MEM-RD and -MEM-WR asserted together
   R2  two or more data-bus drivers in one step
   L1  a load (-AC-LD, REG-LD-LO/HI, -TMP-REG-LD0/1, LD-INS-REG, BRANCH-LD-LO/HI, INT-LD-LO/HI) in a step with no data driver
   L2  a load whose data source appears in the same step it is latched (setup time = one pipeline delay + memory access)
   I1  the register being incremented/decremented is the one on the address bus while a WRITE strobe is asserted
   E1  no UCODE-COUNT-RESET within 64 steps; E2 steps after the reset with anything asserted (dead code)
   S1  steps where nothing at all is asserted except -VMA (idle steps, a speed cost)
Output: docs/isa/MICROCODE-REVIEW.md, docs/isa/steps.txt (per-opcode per-step asserted signals, for human/agent review).
"""
import os, re, sys, collections
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from ucode_wavedrom import signal_table, microcode, opcode_names, active, asm_forms

DATA_DRIVERS = ["-AC-RD", "-REG-RD-LO", "-REG-RD-HI", "-TMP-REG-RD0", "-TMP-REG-RD1", "-BRANCH-RD", "-MEM-RD", "-IO-RD"]
LOADS = ["-AC-LD", "REG-LD-LO", "REG-LD-HI", "-TMP-REG-LD0", "-TMP-REG-LD1", "LD-INS-REG", "BRANCH-LD-LO", "BRANCH-LD-HI", "INT-LD-LO", "INT-LD-HI"]
QUIET = {"-VMA", "OUT-OFF", "OUT-ON", "SPARE3"}

def main():
    sig, recs, names = signal_table(), microcode(), opcode_names()
    S = {n: (b, bt) for n, b, bt in sig}
    forms = asm_forms()
    report = ["# Microcode review (mechanical pass) — %s\n" % __import__("time").strftime("%Y-%m-%d"),
              "Generated by `tools/ucode_review.py` from `firmware/microcode/ucode-generator2/test.hex`. Rules are in the script's docstring;",
              "the hardware model behind them is the one used for `docs/isa/` (pipeline registers apply a step's word for the whole step,",
              "memory writes happen while -MEM-WR is low, the address bus follows the register selected by ADDR-REG-ID).",
              "Register families are checked on every member (all 256 records that hold microcode).\n"]
    steps_txt = []
    totals = collections.Counter(); per_op = {}
    for op in range(256):
        w = recs.get(op)
        if not w or not any(w): continue
        steps = [w[i * 8:i * 8 + 8] for i in range(64)]
        def on(i, n): return n in S and active(steps[i], S[n][0], S[n][1], n)
        def bus(i, prefix): return sum(((steps[i][S[nm][0]] >> S[nm][1]) & 1) << int(nm[-1]) for nm in S if re.fullmatch(prefix + r"\d", nm))
        last = next((i for i in range(64) if on(i, "UCODE-COUNT-RESET")), None)
        n = (last + 1) if last is not None else 64
        base = op & ~7 if any(op & ~7 == k and "Rn" in forms.get(v, ("",))[0] for k, v in names.items()) else op
        name = names.get(op) or (names.get(base, "?") + " R%d" % (op & 7) if base in names else "OP%02X" % op)
        F = []
        # per-step facts
        drivers = [[d for d in DATA_DRIVERS if on(i, d)] for i in range(n)]
        addr_src = [bus(i, "ADDR-REG-ID") for i in range(n)]
        inc = [(bus(i, "REG-RD-ID") if on(i, "-REG-FUNC-RD") and (on(i, "-REG-UP") or on(i, "-REG-DN")) else None) for i in range(n)]
        load_reg = [(bus(i, "REG-LD-ID") if on(i, "-REG-FUNC-LD") and (on(i, "REG-LD-LO") or on(i, "REG-LD-HI")) else None) for i in range(n)]
        wr = [on(i, "-MEM-WR") or on(i, "-IO-WR") for i in range(n)]
        for i in range(n):
            if wr[i]:
                changes = []
                if i > 0 and wr[i - 1] and addr_src[i] != addr_src[i - 1]: changes.append("address source %X->%X" % (addr_src[i - 1], addr_src[i]))
                if inc[i] == addr_src[i]: changes.append("addressed register R%X incremented/decremented this step" % addr_src[i])
                if load_reg[i] == addr_src[i]: changes.append("addressed register R%X loaded this step" % addr_src[i])
                if i > 0 and wr[i - 1] and (inc[i - 1] == addr_src[i - 1]): changes.append("addressed register changed at the end of the previous asserted step")
                if changes: F.append(("W1", i, "-MEM-WR/-IO-WR asserted while the address changes: " + "; ".join(changes)))
                if not drivers[i]: F.append(("W2", i, "-MEM-WR/-IO-WR asserted with nothing driving the data bus"))
                elif i > 0 and wr[i - 1] and drivers[i] != drivers[i - 1]: F.append(("W2", i, "data source changes while the write strobe is asserted: %s -> %s" % (drivers[i - 1], drivers[i])))
                if on(i, "-MEM-WR") and not on(i, "-VMA"): F.append(("W3", i, "-MEM-WR without -VMA"))
            if on(i, "-MEM-RD") and not on(i, "-VMA"): F.append(("W3", i, "-MEM-RD without -VMA"))
            if len(drivers[i]) > 1: F.append(("R2", i, "several data-bus drivers at once: %s" % drivers[i]))
            if on(i, "-MEM-RD") and on(i, "-MEM-WR"): F.append(("R1", i, "-MEM-RD and -MEM-WR asserted together"))   # -MEM-RD + -IO-WR is how OUTI moves a byte from memory to a port
            loads = [l for l in LOADS if on(i, l)]
            if loads and not drivers[i]: F.append(("L1", i, "load %s with nothing driving the data bus" % loads))
            if loads and drivers[i] and (i == 0 or drivers[i - 1] != drivers[i]): F.append(("L2", i, "load %s in the same step its data source %s first appears" % (loads, drivers[i])))
            if wr[i] and inc[i] is not None and inc[i] == addr_src[i]: F.append(("I1", i, "R%X incremented/decremented while it drives the address of a WRITE" % inc[i]))   # during reads only a same-step load would matter (L2)
            asserted = [nm for nm in S if on(i, nm) and not re.fullmatch(r"(REG-RD-ID|REG-LD-ID|ADDR-REG-ID|IOADDR|ALU)\d", nm)]
            if not (set(asserted) - QUIET): F.append(("S1", i, "idle step"))
            steps_txt.append("%-12s step %2d: %s" % (name, i, ", ".join(asserted + ["ADDR-REG-ID=%X" % addr_src[i], "REG-RD-ID=%X" % bus(i, "REG-RD-ID"), "REG-LD-ID=%X" % bus(i, "REG-LD-ID"), "ALU=%X" % bus(i, "ALU")])))
        if last is None: F.append(("E1", 63, "no UCODE-COUNT-RESET: the step counter runs to 63"))
        else:
            tail = [i for i in range(last + 1, 64) if any(steps[i])]   # the generator zero-pads after the reset; a non-zero word there is real dead microcode
            if tail: F.append(("E2", last + 1, "%d steps after the count reset still hold asserted signals (dead microcode)" % len(tail)))
        per_op[op] = (name, n, F)
        for code, _, _ in F: totals[code] += 1
    open(os.path.join(ROOT, "docs/isa/steps.txt"), "w").write("\n".join(steps_txt) + "\n")
    report.append("Totals by rule: " + ", ".join("%s %d" % kv for kv in sorted(totals.items())) + "\n")
    report.append("| Opcode | Mnemonic | Steps | Findings |\n|---|---|---|---|")
    for op, (name, n, F) in sorted(per_op.items()):
        codes = collections.Counter(c for c, _, _ in F)
        report.append("| $%02X | %s | %d | %s |" % (op, name, n, ", ".join("%s x%d" % kv for kv in sorted(codes.items())) or "clean"))
    report.append("\n## Details (idle steps S1 listed as counts only)\n")
    for op, (name, n, F) in sorted(per_op.items()):
        det = [(c, i, t) for c, i, t in F if c != "S1"]; idle = [i for c, i, t in F if c == "S1"]
        if not det and not idle: continue
        report.append("### $%02X %s (%d steps)%s" % (op, name, n, ("  idle steps: %s" % idle) if idle else ""))
        for c, i, t in det: report.append("- %s step %d: %s" % (c, i, t))
        report.append("")
    open(os.path.join(ROOT, "docs/isa/MICROCODE-REVIEW.md"), "w").write("\n".join(report) + "\n")
    print("opcodes reviewed: %d | totals: %s" % (len(per_op), dict(totals)))

if __name__ == "__main__": main()
